"""add columd to table goods

Revision ID: 0d7be0eaaf01
Revises: c4e5de1c0ce4
Create Date: 2023-06-21 22:03:30.215223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7be0eaaf01'
down_revision = 'c4e5de1c0ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'price')
    # ### end Alembic commands ###
