"""create user

Revision ID: 6f48303d8ae3
Revises: 0d7be0eaaf01
Create Date: 2023-07-08 22:30:28.396449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f48303d8ae3'
down_revision = '0d7be0eaaf01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
