"""add email and compaign_id for user

Revision ID: 7927c292901f
Revises: 9de26682bf63
Create Date: 2023-07-09 17:08:25.463532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7927c292901f'
down_revision = '9de26682bf63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('compaign_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'compaign_id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
