"""add email for user

Revision ID: 9de26682bf63
Revises: f65d1965d2d1
Create Date: 2023-07-09 17:04:15.585788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de26682bf63'
down_revision = 'f65d1965d2d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
